name: Build and Test
on:
  push:
    branches:
      - "main"
      - "release/v*"
    paths-ignore:
      - "**/*.png"
  pull_request:
    branches:
      - "main"
      - "release/v*"
    paths-ignore:
      - "**/*.png"

permissions:
  contents: read

jobs:
  # Check if there are changes that require running the test jobs
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      run_test_workflow: ${{ steps.check-changes.outputs.run_test_workflow }}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        if: github.event_name == 'pull_request'
        id: check-changes
        with:
          filters: |
            run_test_workflow:
            - "!?(site|release-notes)/**"

  dump-output:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Dump output
        run: echo "${{ needs.changes.outputs.run_test_workflow }}"

  test-job:
    runs-on: ubuntu-latest
    needs: dump-output
    if: ${{ needs.changes.outputs.run_test_workflow == 'true' }}
    steps:
      - name: Skip test workflow
        run: echo "run test job"
